services:
    Amontreuil\exceptionhandlermodule\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
